// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzRX02jAAUnudKo1FHJ3tRyZhAYJQNQ1k',
    appId: '1:777547089744:web:5ddbcf4d6bb6ae83724e55',
    messagingSenderId: '777547089744',
    projectId: 'notes-shivamidolboy1',
    authDomain: 'notes-shivamidolboy1.firebaseapp.com',
    storageBucket: 'notes-shivamidolboy1.firebasestorage.app',
    measurementId: 'G-6VMK0DKWQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBESTzqvuUHjl3sDF41X5GTokcuUhbA7HA',
    appId: '1:777547089744:android:1b2d38411fd44b06724e55',
    messagingSenderId: '777547089744',
    projectId: 'notes-shivamidolboy1',
    storageBucket: 'notes-shivamidolboy1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOvikKQNawMGdusBRlVwW8e4x4MjWGrVE',
    appId: '1:777547089744:ios:f327a471c097c6b5724e55',
    messagingSenderId: '777547089744',
    projectId: 'notes-shivamidolboy1',
    storageBucket: 'notes-shivamidolboy1.firebasestorage.app',
    iosBundleId: 'com.finislitmyfriend.notes',
  );
}
